database:
  url: jdbc:mariadb://localhost:3306/mydb
  user: user
  password: user_password
  driver: org.mariadb.jdbc.Driver
  dialect: org.hibernate.dialect.MariaDBDialect
  hbm2ddl: update
  showSql: true
  formatSql: true
plugin:
  saveFilepath: loginPluginRes/players.json  # Используется для миграции в prod