name: Java CI with Maven

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MARIADB_DATABASE: Joupen
          MARIADB_USER: user
          MARIADB_PASSWORD: user_password
          MARIADB_ROOT_PASSWORD: root_password
        options: >-
          --health-cmd="mariadb-admin --user=root --password=root_password ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=12

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Install MariaDB client (for wait/check)
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-client

      - name: Wait for MariaDB to be ready
        run: |
          for i in {1..40}; do
            if mariadb-admin --host=mariadb --port=3306 --user=root --password=root_password ping; then
              echo "MariaDB is ready!"
              break
            fi
            echo "Waiting for MariaDB... ($i/40)"
            sleep 3
          done

      # 1) Liquibase migrations
      - name: Run Liquibase migrations (Maven plugin)
        run: |
          mvn -B -P liquibase-update \
            -Ddatabase.url="jdbc:mariadb://mariadb:3306/Joupen" \
            -Ddatabase.user="user" \
            -Ddatabase.password="user_password" \
            -Ddatabase.driver="org.mariadb.jdbc.Driver" \
            -Ddatabase.schema="Joupen" \
            org.liquibase:liquibase-maven-plugin:4.27.0:update

      # 2) jOOQ codegen
      - name: Generate jOOQ code
        run: |
          mvn -B generate-sources \
            -Ddatabase.url="jdbc:mariadb://mariadb:3306/Joupen" \
            -Ddatabase.user="user" \
            -Ddatabase.password="user_password" \
            -Ddatabase.driver="org.mariadb.jdbc.Driver" \
            -Ddatabase.schema="Joupen"

      # 3) Unit + Integration tests, Package
      - name: Test & Package
        run: |
          mvn -B verify \
            -Ddatabase.url="jdbc:mariadb://mariadb:3306/Joupen" \
            -Ddatabase.user="user" \
            -Ddatabase.password="user_password" \
            -Ddatabase.driver="org.mariadb.jdbc.Driver" \
            -Ddatabase.schema="Joupen"

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: joupen-plugin-jars
          path: |
            target/original-JoupenPlugin-*.jar
            target/JoupenPlugin-*.jar

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/*.xml
            target/failsafe-reports/*.xml
