name: Java CI with Maven

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Test & Package
        run: |
          mvn -B verify
          # Проверка генерации jOOQ кода
          if ls target/generated-sources/jooq/org/joupen/jooq/generated/tables/*.java 2>/dev/null; then
            echo "jOOQ код успешно сгенерирован (найдены schema-less таблицы)"
          else
            echo "Ошибка: jOOQ код не сгенерирован или не является schema-less"
            exit 1
          fi

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: joupen-plugin-jars
          path: |
            target/original-JoupenPlugin-*.jar
            target/JoupenPlugin-*.jar