name: Java CI with Maven

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean compile

      - name: Run tests
        run: mvn -B test

      - name: Package application
        run: mvn -B package -DskipTests

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: joupen-plugin-jars
          path: |
            target/*.jar