name: Java CI with Maven

on:
  push:
    branches: [ "**" ]  # Все ветки
  pull_request:
    branches: [ "**" ]  # Все ветки для PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run unit tests
        run: mvn -B test
      - name: Run integration tests
        run: mvn -B verify
      - name: Build with Maven
        run: mvn -B package
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/*.xml
            target/failsafe-reports/*.xml